# Practice 04 - NumPy array

In [2]:
# import the library
import numpy as np

In [3]:
lst=[1,2,3,4]
arr=np.array(lst)

In [4]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(4,)

In [7]:
lst1=[1,2,3,4,5]
lst2=[4,5,6,8,9]
lst3=[7,8,9,4,5]

arr1 = np.array([lst1,lst2,lst3])

In [8]:
arr1

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 8, 9],
       [7, 8, 9, 4, 5]])

In [9]:
type(arr1)

numpy.ndarray

In [10]:
arr1.shape

(3, 5)

In [11]:
# indexing

arr1

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 8, 9],
       [7, 8, 9, 4, 5]])

In [13]:
arr1[0]

array([1, 2, 3, 4, 5])

In [17]:
# change the element
arr1[0][0] = 9

In [18]:
arr1

array([[9, 2, 3, 4, 5],
       [4, 5, 6, 8, 9],
       [7, 8, 9, 4, 5]])

In [20]:
#specify the range

arr1[0:2]

array([[9, 2, 3, 4, 5],
       [4, 5, 6, 8, 9]])

In [23]:
# it will print from last

arr1[::-1]

array([[7, 8, 9, 4, 5],
       [4, 5, 6, 8, 9],
       [9, 2, 3, 4, 5]])

In [25]:
# here : means all rows, also use comma in between [row:col]

arr1

array([[9, 2, 3, 4, 5],
       [4, 5, 6, 8, 9],
       [7, 8, 9, 4, 5]])

In [46]:
arr1[:,1]

array([2, 5, 8])

In [49]:
arr1[:,0:3]

array([[9, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
arr1[:,:3]

array([[9, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
# more indexing

arr1[1:,:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [66]:
arr1[1:2,:3]

array([[4, 5, 6]])

In [68]:
arr1[:2,1:3]

array([[2, 3],
       [5, 6]])

In [69]:
arr1

array([[9, 2, 3, 4, 5],
       [4, 5, 6, 8, 9],
       [7, 8, 9, 4, 5]])

In [72]:
arr1[1:3,3:]

array([[8, 9],
       [4, 5]])

In [81]:
# Exploratory Data Analysis

lst2 =[1,2,3,4,5,6]

In [87]:
arr2 = np.array(lst2)

In [88]:
arr2.shape

(6,)

In [91]:
# saving time from donig for loop
arr2>4

array([False, False, False, False,  True,  True])

In [93]:
# this will the particualr no. greater than 4
arr2[arr2>4]

array([5, 6])

In [95]:
#reshape
arr1

array([[9, 2, 3, 4, 5],
       [4, 5, 6, 8, 9],
       [7, 8, 9, 4, 5]])

In [96]:
arr1.reshape(5,3)

array([[9, 2, 3],
       [4, 5, 4],
       [5, 6, 8],
       [9, 7, 8],
       [9, 4, 5]])

In [100]:
# another mechanism to create array
# arange- (start, stop, step)

np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
np.arange(2,15,2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [107]:
# can also be reshape in 2 dimention (row, column)

np.arange(1,32,2).reshape(2,8)

array([[ 1,  3,  5,  7,  9, 11, 13, 15],
       [17, 19, 21, 23, 25, 27, 29, 31]])

In [122]:
# also we can convert it into 3rd dimention (block, row, column)

np.arange(1,33,1).reshape(2,4,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]])

In [123]:
# numerical

arr1

array([[9, 2, 3, 4, 5],
       [4, 5, 6, 8, 9],
       [7, 8, 9, 4, 5]])

In [124]:
arr1*2

array([[18,  4,  6,  8, 10],
       [ 8, 10, 12, 16, 18],
       [14, 16, 18,  8, 10]])

In [125]:
arr1

array([[9, 2, 3, 4, 5],
       [4, 5, 6, 8, 9],
       [7, 8, 9, 4, 5]])

In [126]:
arr2

array([1, 2, 3, 4, 5, 6])

In [128]:
arr1*arr1

array([[81,  4,  9, 16, 25],
       [16, 25, 36, 64, 81],
       [49, 64, 81, 16, 25]])

In [131]:
# another inbuilt funtions

np.ones((5,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [132]:
np.zeros((6,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [137]:
# random creation of no.

np.random.randint(10,20)

15

In [145]:
# also provide size and shape

np.random.randint(10,20,6).reshape(3,2)

array([[11, 15],
       [16, 15],
       [17, 13]])

In [146]:
# it will also generate no.s between 0-1

np.random.random_sample((4,5))

array([[0.48850962, 0.78888882, 0.27461219, 0.22393974, 0.49476001],
       [0.09588428, 0.45721216, 0.58872219, 0.91091783, 0.80732783],
       [0.6698484 , 0.9671502 , 0.99660775, 0.24322139, 0.87793452],
       [0.4710236 , 0.83882318, 0.18176556, 0.40289086, 0.88100334]])