# Tutorial 08 - Numpy Array

In [1]:
#import the library

import numpy as np

In [3]:
lst=[1,2,3,4]
arr=np.array(lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(4,)

In [7]:
lst1=[1,2,3,4,5]
lst2=[2,3,5,6,4]
lst3=[7,8,9,4,5]

arr1=np.array([lst1,lst2,lst3])

In [9]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 5, 6, 4],
       [7, 8, 9, 4, 5]])

In [8]:
arr1.shape

(3, 5)

In [11]:
#indexing
arr

array([1, 2, 3, 4])

In [13]:
arr[2]

3

In [16]:
# changing element
arr[3]=8

In [15]:
arr

array([1, 2, 3, 8])

In [18]:
# specify range

arr[0:3]

array([1, 2, 3])

In [19]:
arr[-1]

8

In [20]:
arr[:-1]

array([1, 2, 3])

In [23]:
# it will print from last
arr[::-1]

array([8, 3, 2, 1])

In [25]:
# it will jump
arr[::-2]

array([8, 2])

In [26]:
# in 2 dimention

arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 5, 6, 4],
       [7, 8, 9, 4, 5]])

In [49]:
# here : means all rows, also use comman in between [rows:col]
arr1[:,1]

array([2, 3, 8])

In [32]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 5, 6, 4],
       [7, 8, 9, 4, 5]])

In [33]:
arr1[1:,1:3]

array([[3, 5],
       [8, 9]])

In [34]:
arr1[1:,2:4]

array([[5, 6],
       [9, 4]])

In [37]:
arr1[:2,2:4]

array([[3, 4],
       [5, 6]])

In [48]:
arr1[1:,2:]

array([[5, 6, 4],
       [9, 4, 5]])

In [52]:
arr1[2:,2:]

array([[9, 4, 5]])

In [58]:
arr1[:,:3]

array([[1, 2, 3],
       [2, 3, 5],
       [7, 8, 9]])

In [59]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 5, 6, 4],
       [7, 8, 9, 4, 5]])

In [64]:
arr1[:1,:3]

array([[1, 2, 3]])

In [66]:
arr1[2:,:3]

array([[7, 8, 9]])

In [67]:
# EDA

arr

array([1, 2, 3, 8])

In [68]:
arr>4

array([False, False, False,  True])

In [70]:
#picking particular no using condition, saving time from doing for loop
arr[arr>4]

array([8])

In [71]:
arr1.shape

(3, 5)

In [72]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 5, 6, 4],
       [7, 8, 9, 4, 5]])

In [74]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 5, 6],
       [4, 7, 8],
       [9, 4, 5]])

In [78]:
## another mechanism to create array
## arange - (start,stop,step)

np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [94]:
#can also do reshape

np.arange(1,28,2).reshape(2,7)

array([[ 1,  3,  5,  7,  9, 11, 13],
       [15, 17, 19, 21, 23, 25, 27]])

In [95]:
# also we can convert into 3rd dimention

np.arange(1,28,2).reshape(2,7,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13]],

       [[15],
        [17],
        [19],
        [21],
        [23],
        [25],
        [27]]])

In [96]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 5, 6, 4],
       [7, 8, 9, 4, 5]])

In [98]:
# numerical

arr1*2

array([[ 2,  4,  6,  8, 10],
       [ 4,  6, 10, 12,  8],
       [14, 16, 18,  8, 10]])

In [99]:
arr1*arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 25, 36, 16],
       [49, 64, 81, 16, 25]])

In [102]:
# another inbuilt functions, np.ones()

np.ones((5,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [103]:
np.zeros((5,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [107]:
# random creation

np.random.randint(10,100)

87

In [116]:
# also provide size and reshape

np.random.randint(10,100,4).reshape(2,2)

array([[82, 40],
       [96, 39]])

In [114]:
# standard normal distribution

np.random.randn(3,2)

array([[ 0.94374076,  0.57698745],
       [ 0.58460212, -0.30433628],
       [-0.94081019,  0.9858856 ]])

In [117]:
# it will generate no. between 0-1

np.random.random_sample((3,2))

array([[0.00639207, 0.30878735],
       [0.86796383, 0.33303905],
       [0.01303669, 0.41129816]])