# Tutorial 08 - python pandas library - Part 01

in this part we are going to lean about

1. Pandas Dataframe
2. Pandas Series
3. Pandas Basic Operations

In [2]:
import pandas as pd
import numpy as np

In [4]:
## lets do dataframe from scratch

np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
## lets convert it Dataframe creation

df = pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["row01","row02","row03",
                                                           "row04","row05"],columns=["column01",
                                                                                     "column02","column03",
                                                                                     "column04"])

In [17]:
df

column01  column02  column03  column04
row01         0         1         2         3
row02         4         5         6         7
row03         8         9        10        11
row04        12        13        14        15
row05        16        17        18        19

In [18]:
#if you want to see top 2 rows use this

df.head(2)

column01  column02  column03  column04
row01         0         1         2         3
row02         4         5         6         7

In [19]:
# if you want to see lst 2 rows use this

df.tail(2)

column01  column02  column03  column04
row04        12        13        14        15
row05        16        17        18        19

In [20]:
type(df)

pandas.core.frame.DataFrame

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row01 to row05
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   column01  5 non-null      int32
 1   column02  5 non-null      int32
 2   column03  5 non-null      int32
 3   column04  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [22]:
df.describe()

column01   column02   column03   column04
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

#### indexing techniques
- direct by using column name
- rowindex [loc]
- row index column index number  [iloc]


In [23]:
df

column01  column02  column03  column04
row01         0         1         2         3
row02         4         5         6         7
row03         8         9        10        11
row04        12        13        14        15
row05        16        17        18        19

In [28]:
# by using column names

df[['column01','column02','column03']]

column01  column02  column03
row01         0         1         2
row02         4         5         6
row03         8         9        10
row04        12        13        14
row05        16        17        18

In [26]:
df['column01']

row01     0
row02     4
row03     8
row04    12
row05    16
Name: column01, dtype: int32

In [30]:
# rowindex [loc]

df.loc['row02']

column01    4
column02    5
column03    6
column04    7
Name: row02, dtype: int32

In [33]:
df.loc[['row02','row03']]

column01  column02  column03  column04
row02         4         5         6         7
row03         8         9        10        11

In [34]:
# row index column index number [iloc]

df

column01  column02  column03  column04
row01         0         1         2         3
row02         4         5         6         7
row03         8         9        10        11
row04        12        13        14        15
row05        16        17        18        19

In [45]:
df.iloc[2:4,0:2]

column01  column02
row03         8         9
row04        12        13

In [46]:
df.iloc[3:,2:]

column03  column04
row04        14        15
row05        18        19

In [47]:
df.iloc[1:2,2:3]

column03
row02         6

#### convert data frame into arrays

In [48]:
df

column01  column02  column03  column04
row01         0         1         2         3
row02         4         5         6         7
row03         8         9        10        11
row04        12        13        14        15
row05        16        17        18        19

In [49]:
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

#### pandas basic Operations

In [50]:
df

column01  column02  column03  column04
row01         0         1         2         3
row02         4         5         6         7
row03         8         9        10        11
row04        12        13        14        15
row05        16        17        18        19

In [61]:
# sum() it will count the sum of null value
df.isnull().sum()

column01    0
column02    0
column03    0
column04    0
dtype: int64

In [62]:
#For Example

df1 = pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["row01","row02"],columns=["column01","column02","column03"])

In [63]:
df1

column01  column02  column03
row01         1       NaN         2
row02         1       3.0         4

In [64]:
df1.isnull()

column01  column02  column03
row01     False      True     False
row02     False     False     False

In [67]:
df1.isnull().sum()

column01    0
column02    1
column03    0
dtype: int64

In [73]:
# if you want boolean here 0 means false and 1 means true
df1.isnull().sum()==0

column01     True
column02    False
column03     True
dtype: bool

In [85]:
df

column01  column02  column03  column04
row01         0         1         2         3
row02         4         5         6         7
row03         8         9        10        11
row04        12        13        14        15
row05        16        17        18        19

In [90]:
# in this you can see how many times a no. is present in column or row

df["column02"].value_counts()

column02
1     1
5     1
9     1
13    1
17    1
Name: count, dtype: int64

In [87]:
#here you can find the unique no.s

df["column03"].unique()

array([ 2,  6, 10, 14, 18])

In [93]:
#another operation

df>5

column01  column02  column03  column04
row01     False     False     False     False
row02     False     False      True      True
row03      True      True      True      True
row04      True      True      True      True
row05      True      True      True      True

In [96]:
# wants to find which one is greater than 5 then

df[df>5]

column01  column02  column03  column04
row01       NaN       NaN       NaN       NaN
row02       NaN       NaN       6.0       7.0
row03       8.0       9.0      10.0      11.0
row04      12.0      13.0      14.0      15.0
row05      16.0      17.0      18.0      19.0

In [97]:
#also find for particular column or row

df["column04"]>10

row01    False
row02    False
row03     True
row04     True
row05     True
Name: column04, dtype: bool

In [98]:
# that are

df[df["column04"]>10]

column01  column02  column03  column04
row03         8         9        10        11
row04        12        13        14        15
row05        16        17        18        19